services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:myfluveny@mongo:27017/fluvenydb?authSource=admin&authMechanism=SCRAM-SHA-256
    networks:
      - fluveny-net

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - bd-mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: myfluveny
    ports:
      - 29017:27017
    networks:
      - fluveny-net

volumes:
  bd-mongodb:

networks:
  fluveny-net:
